import React from "react";
import style from "../../Styles/privacyPolicy.module.css";

const PrivacyPolicy = () => {
  return (
    <div>
      <div className={style.title}>
        <h2>Privacy Policy</h2>
        <h4>Effective date: 2021-06-01</h4>
      </div>
      <div className="container">
        <div className={style.privacyContent}>
          <h4>1. Introduction</h4>
          <p>
            Welcome to KOWI FASHION PRIVATE LIMITED. KOWI FASHION PRIVATE
            LIMITED (“us”, “we”, or “our”) operates kowi.in (hereinafter
            referred to as “Service”). Our Privacy Policy governs your visit to
            kowi.in, and explains how we collect, safeguard and disclose
            information that results from your use of our Service. We use your
            data to provide and improve Service. By using Service, you agree to
            the collection and use of information in accordance with this
            policy. Unless otherwise defined in this Privacy Policy, the terms
            used in this Privacy Policy have the same meanings as in our Terms
            and Conditions.
            <br />
            <br />
            Our Terms and Conditions (“Terms”) govern all use of our Service and
            together with the Privacy Policy constitutes your agreement with us
            (“agreement”).
          </p>
        </div>
        <div className={style.privacyContent}>
          <h4>2. Definitions</h4>
          <p>
            SERVICE means the kowi.in website operated by KOWI FASHION PRIVATE
            LIMITED.
            <br />
            <br />
            PERSONAL DATA means data about a living individual who can be
            identified from those data (or from those and other information
            either in our possession or likely to come into our possession).
            <br />
            <br />
            USAGE DATA is data collected automatically either generated by the
            use of Service or from Service infrastructure itself (for example,
            the duration of a page visit).
            <br />
            <br />
            COOKIES are small files stored on your device (computer or mobile
            device).
            <br />
            <br />
            DATA CONTROLLER means a natural or legal person who (either alone or
            jointly or in common with other persons) determines the purposes for
            which and the manner in which any personal data are, or are to be,
            processed. For the purpose of this Privacy Policy, we are a Data
            Controller of your data.
            <br />
            <br />
            DATA PROCESSORS (OR SERVICE PROVIDERS) means any natural or legal
            person who processes the data on behalf of the Data Controller. We
            may use the services of various Service Providers in order to
            process your data more effectively.
            <br />
            <br />
            DATA SUBJECT is any living individual who is the subject of Personal
            Data.
            <br />
            <br />
            THE USER is the individual using our Service.
            <br />
            <br />
            The User corresponds to the Data Subject, whois the subject of
            Personal Data
          </p>
        </div>
        <div className={style.privacyContent}>
          <h4>3. Information Collection and Use</h4>
          <p>
            We collect several different types of information for various
            purposes to provide and improve our Service to you.
          </p>
        </div>
        <div className={style.privacyContent}>
          <h4>4. Types of Data Collected</h4>
          <p>
            <b>Personal Data</b>
            <br />
            While using our Service, we may ask you to provide us with certain
            personally identifiable information that can be used to contact or
            identify you (“Personal Data”). Personally identifiable information
            may include, but is not limited to:<b>1.</b> Email address <br />{" "}
            <b>2.</b> First name and last name <br /> <b>3.</b> Phone number{" "}
            <br /> <b>4.</b> Address, Country, State, Province, ZIP/Postal code,
            City <br /> <b>5.</b> Cookies and Usage Data <br /> We may use your
            Personal Data to contact you with newsletters, marketing or
            promotional materials and other information that may be of interest
            to you. You may opt out of receiving any, or all, of these
            communications from us by following the unsubscribe link. <br />{" "}
            <br /> <b>Usage Data</b> <br /> We may also collect information that
            your browser sends whenever you visit our Service or when you access
            Service by or through any device (“Usage Data”). This Usage Data may
            include information such as your computer’s Internet Protocol
            address (e.g. IP address), browser type, browser version, the pages
            of our Service that you visit, the time and date of your visit, the
            time spent on those pages, unique device identifiers and other
            diagnostic data. When you access Service with a device, this Usage
            Data may include information such as thetype of device you use, your
            device unique ID, the IP address of your device, your device
            operating system, the type of Internet browser you use, unique
            device identifiers and other diagnostic data. <br /> <br />{" "}
            <b>Location Data</b> <br /> We may use and store information about
            your location if you give us permission to do so (“Location Data”).
            We use this data to provide features of our Service, to improve and
            customize our Service. You can enable or disable location services
            when you use our Service at any time by way of your device settings.{" "}
            <br /> <br /> <b>Tracking Cookies Data</b> <br /> We use cookies and
            similar tracking technologies to track the activity on our Service
            and we hold certain information. <br /> Cookies are files with a
            small amount of data which may include an anonymous unique
            identifier. Cookies are sent to your browser from a website and
            stored on your device. Other tracking technologies are also used
            such as beacons, tags and scripts to collect and track information
            and to improve and analyze our Service. <br /> You can instruct your
            browser to refuse all cookies or to indicate when a cookie is being
            sent. However, if you do not accept cookies, you may not be able to
            use some portions of our Service. <br /> Examples of Cookies we use:{" "}
            <br /> <b>1.</b> Session Cookies: We use Session Cookies to operate
            our Service. <br /> <b>2.</b> Preference Cookies: We use Preference
            Cookies to remember your preferences and various settings. <br />{" "}
            <b>3.</b> Security Cookies: We use Security Cookiesfor security
            purpses. <br /> <b>4.</b> Advertising Cookies: Advertising Cookies
            are used to seve you with advertisements that may be relevant to you
            and your interests. <br /> <br /> <b>Other Data</b> <br /> While
            using our Service, we may also collect the following information:
            sex, age, date of birth, place of birth, passport details,
            citizenship, registration at place of residence and actual address,
            telephone number (work, mobile), details of documents on education,
            qualification, professional training, employment agreements, NDA
            agreements, information on bonuses and compensation, information on
            marital status, family members, social security (or other taxpayer
            identification) number, office location and other data.
          </p>
        </div>
        <div className={style.privacyContent}>
          <h4>5. Use of Data</h4>
          <p>
            KOWI FASHION PRIVATE LIMITED uses the collected data for various
            purposes:
            <br />
            <b>1.</b> to provide and maintain our Service; <br />
            <b>2.</b> to notify you about changes to our Service; <br />
            <b>3.</b> to allow you to participate in interactive features of our
            Service when you choose to do so; <br />
            <b>4.</b> to provide customer support; <br />
            <b>5.</b> to gather analysis or valuable information so that we can
            improve our Service; <br />
            <b>7.</b> to monitor the usage of our Service; <br />
            <b>7.</b> to detect, prevent and address technical issues; <br />
            <b>8.</b> to fulfil any other purpose for which you provide it;{" "}
            <br />
            <b>9.</b> to carry out our obligations and enforce our rights
            arising from any contracts entered into between you and us,
            including for billing and collection; <br />
            <b>10.</b> to provide you with notices about your account and/or
            subscription, including expiration and renewal notices,
            email-instructions, etc.; <br />
            <b>11.</b> to provide you with news, special offers and general
            information about other goods, services and events which we offer
            that are similar to those that you have already purchased or
            enquired about unless you have opted not to receive such
            information; <br />
            <b>12.</b> in any other way we may describe when you provide the
            information; <br />
            <b>13.</b> for any other purpose with your consent.
          </p>
        </div>
        <div className={style.privacyContent}>
          <h4>6. Retention of Data</h4>
          <p>
            We will retain your Personal Data only for as long as is necessary
            for the purposes set out in this Privacy Policy. We will retain and
            use your Personal Data to the extent necessary to comply with our
            legal obligations (for example, if we are required to retain your
            data to comply with applicable laws), resolve disputes, and enforce
            our legal agreements and policies. We will also retain Usage Data
            for internal analysis purposes. Usage Data is generally retained for
            a shorter period, except when this data is used to strengthen the
            security or to improve the functionality of our Service, or we are
            legally obligated to retain this data for longer time periods.
          </p>
        </div>
        <div className={style.privacyContent}>
          <h4>7. Transfer of Data</h4>
          <p>
            Your information, including Personal Data, may be transferred to –
            and maintained on – computers located outside of your state,
            province, country or other governmental jurisdiction where the data
            protection laws may differ from those of your jurisdiction. If you
            are located outside india and choose to provide information to us,
            please note that we transfer the data, including Personal Data, to
            india and process it there. Your consent to this Privacy Policy
            followed by your submission of such information represents your
            agreement to that transfer. KOWI FASHION PRIVATE LIMITED will take
            all the steps reasonably necessary to ensure that your data is
            treated securely and in accordance with this Privacy Policy and no
            transfer of your Personal Data will take place to an organisation or
            a country unless there are adequate controls in place including the
            security of your data and other personal information.
          </p>
        </div>
        <div className={style.privacyContent}>
          <h4>8. Disclosure of Data</h4>
          <p>
            We may disclose personal information that we collect, or you
            provide: <br />
            <b>1.</b> Disclosure for Law Enforcement. Under certain
            circumstances, we may be required to disclose your Personal Data if
            required to do so by law or in response to valid requests by public
            authorities. <br />
            <b>2.</b> Business Transaction. If we or our subsidiaries are
            involved in a merger, acquisition or asset sale, your Personal Data
            may be transferred. <br />
            <b>3.</b> Other cases. We may disclose your information also: <br />
            <b>3.1.</b> to our subsidiaries and affiliates; <br />
            <b>3.2.</b> to contractors, service providers, and other third
            parties we use to support our business; <br />
            <b>3.3.</b> to fulfill the purpose for which you provide it; <br />
            <b>3.4.</b>
            for the purpose of including your company’s logo on our website;
            <br />
            <b>3.5.</b> for any other purpose disclosed by us when you provide
            the information; <br />
            <b>3.6.</b> with your consent in any other cases; <br />
            <b>3.7.</b> if we believe disclosure is necessary or appropriate to
            protect the rights, property, or safety of the Company, our
            customers, or others.
          </p>
        </div>
        <div className={style.privacyContent}>
          <h4>9. Security of Data</h4>
          <p>
            The security of your data is important to us but remember that no
            method of transmission over the Internet or method of electronic
            storage is 100% secure. While we strive to use commercially
            acceptable means to protect your Personal Data, we cannot guarantee
            its absolute security.
          </p>
        </div>
        <div className={style.privacyContent}>
          <h4>
            10. Your Data Protection Rights Under General Data Protection
            Regulation (GDPR)
          </h4>
          <p>
            If you are a resident of the European Union (EU) and European
            Economic Area (EEA), you have certain data protection rights,
            covered by GDPR. We aim to take reasonable steps to allow you to
            correct, amend, delete, or limit the use of your Personal Data. If
            you wish to be informed what Personal Data we hold about you and if
            you want it to be removed from our systems, please email us at
            contact@kowi.in. In certain circumstances, you have the following
            data protection rights:
            <br />
            0.1. the right to access, update or to delete the information we
            have on you;
            <br />
            0.2. the right of rectification. You have the right to have your
            information rectified if that information is inaccurate or
            incomplete;
            <br />
            0.3. the right to object. You have the right to object to our
            processing of your Personal Data;
            <br />
            0.4. the right of restriction. You have the right to request that we
            restrict the processing of your personal information;
            <br />
            0.5. the right to data portability. You have the right to be
            provided with a copy of your Personal Data in a structured,
            machine-readable and commonly used format;
            <br />
            0.6. the right to withdraw consent. You also have the right to
            withdraw your consent at any time where we rely on your consent to
            process your personal information; Please note that we may ask you
            to verify your identity before responding to such requests. Please
            note, we may not able to provide Service without some necessary
            data. You have the right to complain to a Data Protection Authority
            about our collection and use of your Personal Data. For more
            information, please contact your local data protection authority in
            the European Economic Area (EEA).
          </p>
        </div>
        <div className={style.privacyContent}>
          <h4>
            12. Your Data Protection Rights under the California Consumer
            Privacy Act (CCPA)
          </h4>
          <p>
            If you are a California resident, you are entitled to learn what
            data we collect about you, ask to delete your data and not to sell
            (share) it. To exercise your data protection rights, you can make
            certain requests and ask us:
            <br />
            <b>1.</b> What personal information we have about you. If you make
            this request, we will return to you:
            <br />
            <b>0.1.</b> The categories of personal information we have collected
            about you.
            <br />
            <b>0.2.</b> The categories of sources from which we collect your
            personal information.
            <br />
            <b>0.3.</b> The business or commercial purpose for collecting or
            selling your personal information.
            <br />
            <b>0.4.</b> The categories of third parties with whom we share
            personal information.
            <br />
            <b>0.5.</b> The specific pieces of personal information we have
            collected about you.
            <br />
            <b>0.6.</b> A list of categories of personal information that we
            have sold, along with the category of any other company we sold it
            to. If we have not sold your personal information, we will inform
            you of that fact.
            <br />
            <b>0.7.</b> A list of categories of personal information that we
            have disclosed for a business purpose, along with the category of
            any other company we shared it with. Please note, you are entitled
            to ask us to provide you with this information up to two times in a
            rolling twelve-month period. When you make this request, the
            information provided may be limited to the personal information we
            collected about you in the previous 12 months.
            <br />
            <b>2.</b> To delete your personal information. If you make this
            request, we will delete the personal information we hold about you
            as of the date of your request from our records and direct any
            service providers to do the same. In some cases, deletion may be
            accomplished through de-identification of the information. If you
            choose to delete your personal information, you may not be able to
            use certain functions that require your personal information to
            operate.
            <br />
            <b>3.</b> To stop selling your personal information. We don’t sell
            or rent your personal information to any third parties for any
            purpose. We do not sell your personal information for monetary
            consideration. However, under some circumstances, a transfer of
            personal information to a third party, or within our family of
            companies, without monetary consideration may be considered a “sale”
            under California law. You are the only owner of your Personal Data
            and can request disclosure or deletion at any time. If you submit a
            request to stop selling your personal information, we will stop
            making such transfers.
            <br />
            <br />
            Please note, if you ask us to delete or stop selling your data, it
            may impact your experience with us, and you may not be able to
            participate in certain programs or membership services which require
            the usage of your personal information to function. But in no
            circumstances, we will discriminate against you for exercising your
            rights.
            <br />
            <br />
            To exercise your California data protection rights described above,
            please send your request(s) by email: contact@kowi.in.
            <br />
            <br />
            Your data protection rights, described above, are covered by the
            CCPA, short for the California Consumer Privacy Act. To find out
            more, visit the official California Legislative Information website.
            The CCPA took effect on 01/01/2020.
          </p>
        </div>
        <div className={style.privacyContent}>
          <h4>13. Service Providers</h4>
          <p>
            We may employ third party companies and individuals to facilitate
            our Service (“Service Providers”), provide Service on our behalf,
            perform Service-related services or assist us in analysing how our
            Service is used. These third parties have access to your Personal
            Data only to perform these tasks on our behalf and are obligated not
            to disclose or use it for any other purpose.
          </p>
        </div>
        <div className={style.privacyContent}>
          <h4>14. Analytics</h4>
          <p>
            We may use third-party Service Providers to monitor and analyze the
            use of our Service.
          </p>
        </div>
        <div className={style.privacyContent}>
          <h4>15. CI/CD tools</h4>
          <p>
            We may use third-party Service Providers to automate the development
            process of our Service.
          </p>
        </div>
        <div className={style.privacyContent}>
          <h4>16. Behavioral Remarketing</h4>
          <p>
            We may use remarketing services to advertise on third party websites
            to you after you visited our Service. We and our third-party vendors
            use cookies to inform, optimise and serve ads based on your past
            visits to our Service.
          </p>
        </div>
        <div className={style.privacyContent}>
          <h4>17. Payments</h4>
        </div>
      </div>
    </div>
  );
};

export default PrivacyPolicy;
